name: Type Check

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  mypy:
    runs-on: ubuntu-latest

    steps:
      # Get source code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      # Restore pip cache
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt', '**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Install dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install mypy

      # Restore MyPy cache
      - name: Restore MyPy cache
        uses: actions/cache@v4
        with:
          path: .mypy_cache
          key: mypy-${{ runner.os }}-${{ hashFiles('**/*.py', 'requirements.txt') }}
          restore-keys: |
            mypy-${{ runner.os }}-

      # Run MyPy type checking
      - name: Run MyPy
        run: mypy .